--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.4 (Ubuntu 17.4-1.pgdg24.04+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: api_task; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_task (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    completed boolean NOT NULL
);


ALTER TABLE public.api_task OWNER TO postgres;

--
-- Name: api_task_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: exams_cheatinglog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exams_cheatinglog (
    id bigint NOT NULL,
    exam_id character varying(100) NOT NULL,
    reason text NOT NULL,
    "timestamp" timestamp with time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.exams_cheatinglog OWNER TO postgres;

--
-- Name: exams_cheatinglog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exams_cheatinglog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exams_cheatinglog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exams_codingquestion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exams_codingquestion (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    difficulty character varying(10) NOT NULL,
    starter_code text NOT NULL,
    source character varying(100) NOT NULL,
    points double precision NOT NULL,
    tags jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    language character varying(20) NOT NULL
);


ALTER TABLE public.exams_codingquestion OWNER TO postgres;

--
-- Name: exams_codingquestion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exams_codingquestion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exams_codingquestion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exams_codingtestcase; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exams_codingtestcase (
    id bigint NOT NULL,
    input_data text NOT NULL,
    expected_output text NOT NULL,
    question_id bigint NOT NULL,
    function_name character varying(100) NOT NULL
);


ALTER TABLE public.exams_codingtestcase OWNER TO postgres;

--
-- Name: exams_codingtestcase_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exams_codingtestcase ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exams_codingtestcase_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exams_exam; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exams_exam (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    duration integer NOT NULL,
    course_id bigint,
    CONSTRAINT exams_exam_duration_check CHECK ((duration >= 0))
);


ALTER TABLE public.exams_exam OWNER TO postgres;

--
-- Name: exams_exam_CodingQuestions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."exams_exam_CodingQuestions" (
    id bigint NOT NULL,
    exam_id bigint NOT NULL,
    codingquestion_id bigint NOT NULL
);


ALTER TABLE public."exams_exam_CodingQuestions" OWNER TO postgres;

--
-- Name: exams_exam_CodingQuestions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."exams_exam_CodingQuestions" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."exams_exam_CodingQuestions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exams_exam_MCQQuestions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."exams_exam_MCQQuestions" (
    id bigint NOT NULL,
    exam_id bigint NOT NULL,
    mcqquestion_id bigint NOT NULL
);


ALTER TABLE public."exams_exam_MCQQuestions" OWNER TO postgres;

--
-- Name: exams_exam_MCQQuestions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."exams_exam_MCQQuestions" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."exams_exam_MCQQuestions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exams_exam_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exams_exam ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exams_exam_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exams_mcqquestion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exams_mcqquestion (
    id bigint NOT NULL,
    question_text text NOT NULL,
    option_a character varying(255) NOT NULL,
    option_b character varying(255) NOT NULL,
    option_c character varying(255),
    option_d character varying(255),
    correct_option character varying(1) NOT NULL,
    difficulty character varying(20) NOT NULL,
    language character varying(20) NOT NULL,
    source character varying(100) NOT NULL,
    points double precision NOT NULL
);


ALTER TABLE public.exams_mcqquestion OWNER TO postgres;

--
-- Name: exams_mcqquestion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exams_mcqquestion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exams_mcqquestion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exams_studentexamanswer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exams_studentexamanswer (
    id bigint NOT NULL,
    compressed_answers bytea NOT NULL,
    score double precision NOT NULL,
    submitted_at timestamp with time zone NOT NULL,
    student_id bigint NOT NULL,
    exam_instance_id bigint NOT NULL
);


ALTER TABLE public.exams_studentexamanswer OWNER TO postgres;

--
-- Name: exams_studentexamanswer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exams_studentexamanswer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exams_studentexamanswer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exams_temporaryexaminstance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exams_temporaryexaminstance (
    id bigint NOT NULL,
    start_datetime timestamp with time zone NOT NULL,
    end_datetime timestamp with time zone NOT NULL,
    exam_id bigint NOT NULL,
    track_id bigint,
    branch_id bigint,
    instructor_id bigint
);


ALTER TABLE public.exams_temporaryexaminstance OWNER TO postgres;

--
-- Name: exams_temporaryexaminstance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exams_temporaryexaminstance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exams_temporaryexaminstance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exams_temporaryexaminstance_students; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exams_temporaryexaminstance_students (
    id bigint NOT NULL,
    temporaryexaminstance_id bigint NOT NULL,
    student_id bigint NOT NULL
);


ALTER TABLE public.exams_temporaryexaminstance_students OWNER TO postgres;

--
-- Name: exams_temporaryexaminstance_students_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exams_temporaryexaminstance_students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exams_temporaryexaminstance_students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: labs_lab; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.labs_lab (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    file character varying(100) NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL,
    size character varying(20),
    instructor_id bigint NOT NULL,
    track_id bigint NOT NULL,
    submission_link character varying(200)
);


ALTER TABLE public.labs_lab OWNER TO postgres;

--
-- Name: labs_lab_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.labs_lab ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.labs_lab_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: social_auth_association; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.social_auth_association (
    id bigint NOT NULL,
    server_url character varying(255) NOT NULL,
    handle character varying(255) NOT NULL,
    secret character varying(255) NOT NULL,
    issued integer NOT NULL,
    lifetime integer NOT NULL,
    assoc_type character varying(64) NOT NULL
);


ALTER TABLE public.social_auth_association OWNER TO postgres;

--
-- Name: social_auth_association_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.social_auth_association ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_auth_association_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: social_auth_code; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.social_auth_code (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    code character varying(32) NOT NULL,
    verified boolean NOT NULL,
    "timestamp" timestamp with time zone NOT NULL
);


ALTER TABLE public.social_auth_code OWNER TO postgres;

--
-- Name: social_auth_code_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.social_auth_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_auth_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: social_auth_nonce; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.social_auth_nonce (
    id bigint NOT NULL,
    server_url character varying(255) NOT NULL,
    "timestamp" integer NOT NULL,
    salt character varying(65) NOT NULL
);


ALTER TABLE public.social_auth_nonce OWNER TO postgres;

--
-- Name: social_auth_nonce_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.social_auth_nonce ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_auth_nonce_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: social_auth_partial; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.social_auth_partial (
    id bigint NOT NULL,
    token character varying(32) NOT NULL,
    next_step smallint NOT NULL,
    backend character varying(32) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    data jsonb NOT NULL,
    CONSTRAINT social_auth_partial_next_step_check CHECK ((next_step >= 0))
);


ALTER TABLE public.social_auth_partial OWNER TO postgres;

--
-- Name: social_auth_partial_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.social_auth_partial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_auth_partial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: social_auth_usersocialauth; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.social_auth_usersocialauth (
    id bigint NOT NULL,
    provider character varying(32) NOT NULL,
    uid character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL,
    extra_data jsonb NOT NULL
);


ALTER TABLE public.social_auth_usersocialauth OWNER TO postgres;

--
-- Name: social_auth_usersocialauth_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.social_auth_usersocialauth ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_auth_usersocialauth_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: st_notifications_note; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.st_notifications_note (
    id bigint NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    student_id bigint,
    instructor_id bigint,
    read boolean NOT NULL,
    track_id bigint
);


ALTER TABLE public.st_notifications_note OWNER TO postgres;

--
-- Name: st_notifications_note_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.st_notifications_note ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.st_notifications_note_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: st_notifications_predefinednotification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.st_notifications_predefinednotification (
    id bigint NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.st_notifications_predefinednotification OWNER TO postgres;

--
-- Name: st_notifications_predefinednotification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.st_notifications_predefinednotification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.st_notifications_predefinednotification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: st_notifications_pushsubscription; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.st_notifications_pushsubscription (
    id bigint NOT NULL,
    subscription text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.st_notifications_pushsubscription OWNER TO postgres;

--
-- Name: st_notifications_pushsubscription_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.st_notifications_pushsubscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.st_notifications_pushsubscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_branch; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_branch (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.users_branch OWNER TO postgres;

--
-- Name: users_branch_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_branch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_branch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_course; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_course (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    instructor_id bigint,
    track_id bigint NOT NULL
);


ALTER TABLE public.users_course OWNER TO postgres;

--
-- Name: users_course_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_instructor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_instructor (
    id bigint NOT NULL,
    experience_years integer,
    user_id bigint,
    branch_id bigint,
    CONSTRAINT users_instructor_experience_years_check CHECK ((experience_years >= 0))
);


ALTER TABLE public.users_instructor OWNER TO postgres;

--
-- Name: users_instructor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_instructor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_instructor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_student; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_student (
    id bigint NOT NULL,
    university character varying(100),
    graduation_year integer,
    college character varying(100),
    leetcode_profile character varying(255),
    github_profile character varying(200),
    user_id bigint,
    track_id bigint,
    branch_id bigint,
    inrollment_date date NOT NULL,
    CONSTRAINT users_student_graduation_year_check CHECK ((graduation_year >= 0))
);


ALTER TABLE public.users_student OWNER TO postgres;

--
-- Name: users_student_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_student ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_track; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_track (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.users_track OWNER TO postgres;

--
-- Name: users_track_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_track ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_track_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_track_instructors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_track_instructors (
    id bigint NOT NULL,
    track_id bigint NOT NULL,
    instructor_id bigint NOT NULL
);


ALTER TABLE public.users_track_instructors OWNER TO postgres;

--
-- Name: users_track_instructors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_track_instructors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_track_instructors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(10) NOT NULL,
    email character varying(254) NOT NULL,
    signup_token character varying(32),
    profile_image character varying(100),
    phone_number character varying(15),
    address character varying(100)
);


ALTER TABLE public.users_user OWNER TO postgres;

--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO postgres;

--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO postgres;

--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_task api_task_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_task
    ADD CONSTRAINT api_task_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: exams_cheatinglog exams_cheatinglog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_cheatinglog
    ADD CONSTRAINT exams_cheatinglog_pkey PRIMARY KEY (id);


--
-- Name: exams_codingquestion exams_codingquestion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_codingquestion
    ADD CONSTRAINT exams_codingquestion_pkey PRIMARY KEY (id);


--
-- Name: exams_codingtestcase exams_codingtestcase_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_codingtestcase
    ADD CONSTRAINT exams_codingtestcase_pkey PRIMARY KEY (id);


--
-- Name: exams_exam_CodingQuestions exams_exam_CodingQuestio_exam_id_codingquestion_i_d333b08a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."exams_exam_CodingQuestions"
    ADD CONSTRAINT "exams_exam_CodingQuestio_exam_id_codingquestion_i_d333b08a_uniq" UNIQUE (exam_id, codingquestion_id);


--
-- Name: exams_exam_CodingQuestions exams_exam_CodingQuestions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."exams_exam_CodingQuestions"
    ADD CONSTRAINT "exams_exam_CodingQuestions_pkey" PRIMARY KEY (id);


--
-- Name: exams_exam_MCQQuestions exams_exam_MCQQuestions_exam_id_mcqquestion_id_537fd1af_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."exams_exam_MCQQuestions"
    ADD CONSTRAINT "exams_exam_MCQQuestions_exam_id_mcqquestion_id_537fd1af_uniq" UNIQUE (exam_id, mcqquestion_id);


--
-- Name: exams_exam_MCQQuestions exams_exam_MCQQuestions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."exams_exam_MCQQuestions"
    ADD CONSTRAINT "exams_exam_MCQQuestions_pkey" PRIMARY KEY (id);


--
-- Name: exams_exam exams_exam_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_exam
    ADD CONSTRAINT exams_exam_pkey PRIMARY KEY (id);


--
-- Name: exams_mcqquestion exams_mcqquestion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_mcqquestion
    ADD CONSTRAINT exams_mcqquestion_pkey PRIMARY KEY (id);


--
-- Name: exams_studentexamanswer exams_studentexamanswer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_studentexamanswer
    ADD CONSTRAINT exams_studentexamanswer_pkey PRIMARY KEY (id);


--
-- Name: exams_temporaryexaminstance_students exams_temporaryexaminsta_temporaryexaminstance_id_95fbe3c9_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_temporaryexaminstance_students
    ADD CONSTRAINT exams_temporaryexaminsta_temporaryexaminstance_id_95fbe3c9_uniq UNIQUE (temporaryexaminstance_id, student_id);


--
-- Name: exams_temporaryexaminstance exams_temporaryexaminstance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_temporaryexaminstance
    ADD CONSTRAINT exams_temporaryexaminstance_pkey PRIMARY KEY (id);


--
-- Name: exams_temporaryexaminstance_students exams_temporaryexaminstance_students_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_temporaryexaminstance_students
    ADD CONSTRAINT exams_temporaryexaminstance_students_pkey PRIMARY KEY (id);


--
-- Name: labs_lab labs_lab_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labs_lab
    ADD CONSTRAINT labs_lab_pkey PRIMARY KEY (id);


--
-- Name: social_auth_association social_auth_association_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.social_auth_association
    ADD CONSTRAINT social_auth_association_pkey PRIMARY KEY (id);


--
-- Name: social_auth_association social_auth_association_server_url_handle_078befa2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.social_auth_association
    ADD CONSTRAINT social_auth_association_server_url_handle_078befa2_uniq UNIQUE (server_url, handle);


--
-- Name: social_auth_code social_auth_code_email_code_801b2d02_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.social_auth_code
    ADD CONSTRAINT social_auth_code_email_code_801b2d02_uniq UNIQUE (email, code);


--
-- Name: social_auth_code social_auth_code_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.social_auth_code
    ADD CONSTRAINT social_auth_code_pkey PRIMARY KEY (id);


--
-- Name: social_auth_nonce social_auth_nonce_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.social_auth_nonce
    ADD CONSTRAINT social_auth_nonce_pkey PRIMARY KEY (id);


--
-- Name: social_auth_nonce social_auth_nonce_server_url_timestamp_salt_f6284463_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.social_auth_nonce
    ADD CONSTRAINT social_auth_nonce_server_url_timestamp_salt_f6284463_uniq UNIQUE (server_url, "timestamp", salt);


--
-- Name: social_auth_partial social_auth_partial_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.social_auth_partial
    ADD CONSTRAINT social_auth_partial_pkey PRIMARY KEY (id);


--
-- Name: social_auth_usersocialauth social_auth_usersocialauth_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.social_auth_usersocialauth
    ADD CONSTRAINT social_auth_usersocialauth_pkey PRIMARY KEY (id);


--
-- Name: social_auth_usersocialauth social_auth_usersocialauth_provider_uid_e6b5e668_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.social_auth_usersocialauth
    ADD CONSTRAINT social_auth_usersocialauth_provider_uid_e6b5e668_uniq UNIQUE (provider, uid);


--
-- Name: st_notifications_note st_notifications_note_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.st_notifications_note
    ADD CONSTRAINT st_notifications_note_pkey PRIMARY KEY (id);


--
-- Name: st_notifications_predefinednotification st_notifications_predefinednotification_message_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.st_notifications_predefinednotification
    ADD CONSTRAINT st_notifications_predefinednotification_message_key UNIQUE (message);


--
-- Name: st_notifications_predefinednotification st_notifications_predefinednotification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.st_notifications_predefinednotification
    ADD CONSTRAINT st_notifications_predefinednotification_pkey PRIMARY KEY (id);


--
-- Name: st_notifications_pushsubscription st_notifications_pushsubscription_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.st_notifications_pushsubscription
    ADD CONSTRAINT st_notifications_pushsubscription_pkey PRIMARY KEY (id);


--
-- Name: users_branch users_branch_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_branch
    ADD CONSTRAINT users_branch_name_key UNIQUE (name);


--
-- Name: users_branch users_branch_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_branch
    ADD CONSTRAINT users_branch_pkey PRIMARY KEY (id);


--
-- Name: users_course users_course_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_course
    ADD CONSTRAINT users_course_pkey PRIMARY KEY (id);


--
-- Name: users_instructor users_instructor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_instructor
    ADD CONSTRAINT users_instructor_pkey PRIMARY KEY (id);


--
-- Name: users_instructor users_instructor_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_instructor
    ADD CONSTRAINT users_instructor_user_id_key UNIQUE (user_id);


--
-- Name: users_student users_student_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_student
    ADD CONSTRAINT users_student_pkey PRIMARY KEY (id);


--
-- Name: users_student users_student_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_student
    ADD CONSTRAINT users_student_user_id_key UNIQUE (user_id);


--
-- Name: users_track_instructors users_track_instructors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_track_instructors
    ADD CONSTRAINT users_track_instructors_pkey PRIMARY KEY (id);


--
-- Name: users_track_instructors users_track_instructors_track_id_instructor_id_0b0649ec_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_track_instructors
    ADD CONSTRAINT users_track_instructors_track_id_instructor_id_0b0649ec_uniq UNIQUE (track_id, instructor_id);


--
-- Name: users_track users_track_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_track
    ADD CONSTRAINT users_track_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_email_key UNIQUE (email);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user users_user_signup_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_signup_token_key UNIQUE (signup_token);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: users_user users_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: exams_cheatinglog_user_id_f6ab4356; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX exams_cheatinglog_user_id_f6ab4356 ON public.exams_cheatinglog USING btree (user_id);


--
-- Name: exams_codingtestcase_question_id_7d8bcb41; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX exams_codingtestcase_question_id_7d8bcb41 ON public.exams_codingtestcase USING btree (question_id);


--
-- Name: exams_exam_CodingQuestions_codingquestion_id_4d9dd577; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "exams_exam_CodingQuestions_codingquestion_id_4d9dd577" ON public."exams_exam_CodingQuestions" USING btree (codingquestion_id);


--
-- Name: exams_exam_CodingQuestions_exam_id_8178a596; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "exams_exam_CodingQuestions_exam_id_8178a596" ON public."exams_exam_CodingQuestions" USING btree (exam_id);


--
-- Name: exams_exam_MCQQuestions_exam_id_cb816d76; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "exams_exam_MCQQuestions_exam_id_cb816d76" ON public."exams_exam_MCQQuestions" USING btree (exam_id);


--
-- Name: exams_exam_MCQQuestions_mcqquestion_id_ca16f9ae; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "exams_exam_MCQQuestions_mcqquestion_id_ca16f9ae" ON public."exams_exam_MCQQuestions" USING btree (mcqquestion_id);


--
-- Name: exams_exam_course_id_67ded634; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX exams_exam_course_id_67ded634 ON public.exams_exam USING btree (course_id);


--
-- Name: exams_studentexamanswer_exam_instance_id_9c2e66e9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX exams_studentexamanswer_exam_instance_id_9c2e66e9 ON public.exams_studentexamanswer USING btree (exam_instance_id);


--
-- Name: exams_studentexamanswer_student_id_ddb129c2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX exams_studentexamanswer_student_id_ddb129c2 ON public.exams_studentexamanswer USING btree (student_id);


--
-- Name: exams_temporaryexaminstanc_temporaryexaminstance_id_36455768; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX exams_temporaryexaminstanc_temporaryexaminstance_id_36455768 ON public.exams_temporaryexaminstance_students USING btree (temporaryexaminstance_id);


--
-- Name: exams_temporaryexaminstance_branch_id_17bf8acd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX exams_temporaryexaminstance_branch_id_17bf8acd ON public.exams_temporaryexaminstance USING btree (branch_id);


--
-- Name: exams_temporaryexaminstance_exam_id_6d734dda; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX exams_temporaryexaminstance_exam_id_6d734dda ON public.exams_temporaryexaminstance USING btree (exam_id);


--
-- Name: exams_temporaryexaminstance_instructor_id_b6fda71e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX exams_temporaryexaminstance_instructor_id_b6fda71e ON public.exams_temporaryexaminstance USING btree (instructor_id);


--
-- Name: exams_temporaryexaminstance_students_student_id_379324c2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX exams_temporaryexaminstance_students_student_id_379324c2 ON public.exams_temporaryexaminstance_students USING btree (student_id);


--
-- Name: exams_temporaryexaminstance_track_id_a4a6109f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX exams_temporaryexaminstance_track_id_a4a6109f ON public.exams_temporaryexaminstance USING btree (track_id);


--
-- Name: labs_lab_instructor_id_736a7990; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labs_lab_instructor_id_736a7990 ON public.labs_lab USING btree (instructor_id);


--
-- Name: labs_lab_track_id_c6377096; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX labs_lab_track_id_c6377096 ON public.labs_lab USING btree (track_id);


--
-- Name: social_auth_code_code_a2393167; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX social_auth_code_code_a2393167 ON public.social_auth_code USING btree (code);


--
-- Name: social_auth_code_code_a2393167_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX social_auth_code_code_a2393167_like ON public.social_auth_code USING btree (code varchar_pattern_ops);


--
-- Name: social_auth_code_timestamp_176b341f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX social_auth_code_timestamp_176b341f ON public.social_auth_code USING btree ("timestamp");


--
-- Name: social_auth_partial_timestamp_50f2119f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX social_auth_partial_timestamp_50f2119f ON public.social_auth_partial USING btree ("timestamp");


--
-- Name: social_auth_partial_token_3017fea3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX social_auth_partial_token_3017fea3 ON public.social_auth_partial USING btree (token);


--
-- Name: social_auth_partial_token_3017fea3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX social_auth_partial_token_3017fea3_like ON public.social_auth_partial USING btree (token varchar_pattern_ops);


--
-- Name: social_auth_usersocialauth_uid_796e51dc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX social_auth_usersocialauth_uid_796e51dc ON public.social_auth_usersocialauth USING btree (uid);


--
-- Name: social_auth_usersocialauth_uid_796e51dc_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX social_auth_usersocialauth_uid_796e51dc_like ON public.social_auth_usersocialauth USING btree (uid varchar_pattern_ops);


--
-- Name: social_auth_usersocialauth_user_id_17d28448; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX social_auth_usersocialauth_user_id_17d28448 ON public.social_auth_usersocialauth USING btree (user_id);


--
-- Name: st_notifications_note_instructor_id_2272f5de; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX st_notifications_note_instructor_id_2272f5de ON public.st_notifications_note USING btree (instructor_id);


--
-- Name: st_notifications_note_student_id_7a1ea08a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX st_notifications_note_student_id_7a1ea08a ON public.st_notifications_note USING btree (student_id);


--
-- Name: st_notifications_note_track_id_7ed19623; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX st_notifications_note_track_id_7ed19623 ON public.st_notifications_note USING btree (track_id);


--
-- Name: st_notifications_predefinednotification_message_e11789ef_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX st_notifications_predefinednotification_message_e11789ef_like ON public.st_notifications_predefinednotification USING btree (message text_pattern_ops);


--
-- Name: st_notifications_pushsubscription_user_id_a1254722; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX st_notifications_pushsubscription_user_id_a1254722 ON public.st_notifications_pushsubscription USING btree (user_id);


--
-- Name: users_branch_name_be4ed0e3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_branch_name_be4ed0e3_like ON public.users_branch USING btree (name varchar_pattern_ops);


--
-- Name: users_course_instructor_id_64a94160; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_course_instructor_id_64a94160 ON public.users_course USING btree (instructor_id);


--
-- Name: users_course_track_id_b6f335bc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_course_track_id_b6f335bc ON public.users_course USING btree (track_id);


--
-- Name: users_instructor_branch_id_2a24d57f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_instructor_branch_id_2a24d57f ON public.users_instructor USING btree (branch_id);


--
-- Name: users_student_branch_id_67ef876d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_student_branch_id_67ef876d ON public.users_student USING btree (branch_id);


--
-- Name: users_student_track_id_bdc09d87; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_student_track_id_bdc09d87 ON public.users_student USING btree (track_id);


--
-- Name: users_track_instructors_instructor_id_95191c73; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_track_instructors_instructor_id_95191c73 ON public.users_track_instructors USING btree (instructor_id);


--
-- Name: users_track_instructors_track_id_a895d887; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_track_instructors_track_id_a895d887 ON public.users_track_instructors USING btree (track_id);


--
-- Name: users_user_email_243f6e77_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_email_243f6e77_like ON public.users_user USING btree (email varchar_pattern_ops);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_signup_token_82d9d752_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_signup_token_82d9d752_like ON public.users_user USING btree (signup_token varchar_pattern_ops);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: users_user_username_06e46fe6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_username_06e46fe6_like ON public.users_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exams_cheatinglog exams_cheatinglog_user_id_f6ab4356_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_cheatinglog
    ADD CONSTRAINT exams_cheatinglog_user_id_f6ab4356_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exams_codingtestcase exams_codingtestcase_question_id_7d8bcb41_fk_exams_cod; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_codingtestcase
    ADD CONSTRAINT exams_codingtestcase_question_id_7d8bcb41_fk_exams_cod FOREIGN KEY (question_id) REFERENCES public.exams_codingquestion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exams_exam_CodingQuestions exams_exam_CodingQue_codingquestion_id_4d9dd577_fk_exams_cod; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."exams_exam_CodingQuestions"
    ADD CONSTRAINT "exams_exam_CodingQue_codingquestion_id_4d9dd577_fk_exams_cod" FOREIGN KEY (codingquestion_id) REFERENCES public.exams_codingquestion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exams_exam_CodingQuestions exams_exam_CodingQuestions_exam_id_8178a596_fk_exams_exam_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."exams_exam_CodingQuestions"
    ADD CONSTRAINT "exams_exam_CodingQuestions_exam_id_8178a596_fk_exams_exam_id" FOREIGN KEY (exam_id) REFERENCES public.exams_exam(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exams_exam_MCQQuestions exams_exam_MCQQuesti_mcqquestion_id_ca16f9ae_fk_exams_mcq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."exams_exam_MCQQuestions"
    ADD CONSTRAINT "exams_exam_MCQQuesti_mcqquestion_id_ca16f9ae_fk_exams_mcq" FOREIGN KEY (mcqquestion_id) REFERENCES public.exams_mcqquestion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exams_exam_MCQQuestions exams_exam_MCQQuestions_exam_id_cb816d76_fk_exams_exam_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."exams_exam_MCQQuestions"
    ADD CONSTRAINT "exams_exam_MCQQuestions_exam_id_cb816d76_fk_exams_exam_id" FOREIGN KEY (exam_id) REFERENCES public.exams_exam(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exams_exam exams_exam_course_id_67ded634_fk_users_course_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_exam
    ADD CONSTRAINT exams_exam_course_id_67ded634_fk_users_course_id FOREIGN KEY (course_id) REFERENCES public.users_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exams_studentexamanswer exams_studentexamans_exam_instance_id_9c2e66e9_fk_exams_tem; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_studentexamanswer
    ADD CONSTRAINT exams_studentexamans_exam_instance_id_9c2e66e9_fk_exams_tem FOREIGN KEY (exam_instance_id) REFERENCES public.exams_temporaryexaminstance(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exams_studentexamanswer exams_studentexamanswer_student_id_ddb129c2_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_studentexamanswer
    ADD CONSTRAINT exams_studentexamanswer_student_id_ddb129c2_fk_users_user_id FOREIGN KEY (student_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exams_temporaryexaminstance exams_temporaryexami_branch_id_17bf8acd_fk_users_bra; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_temporaryexaminstance
    ADD CONSTRAINT exams_temporaryexami_branch_id_17bf8acd_fk_users_bra FOREIGN KEY (branch_id) REFERENCES public.users_branch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exams_temporaryexaminstance exams_temporaryexami_instructor_id_b6fda71e_fk_users_ins; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_temporaryexaminstance
    ADD CONSTRAINT exams_temporaryexami_instructor_id_b6fda71e_fk_users_ins FOREIGN KEY (instructor_id) REFERENCES public.users_instructor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exams_temporaryexaminstance_students exams_temporaryexami_student_id_379324c2_fk_users_stu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_temporaryexaminstance_students
    ADD CONSTRAINT exams_temporaryexami_student_id_379324c2_fk_users_stu FOREIGN KEY (student_id) REFERENCES public.users_student(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exams_temporaryexaminstance_students exams_temporaryexami_temporaryexaminstanc_36455768_fk_exams_tem; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_temporaryexaminstance_students
    ADD CONSTRAINT exams_temporaryexami_temporaryexaminstanc_36455768_fk_exams_tem FOREIGN KEY (temporaryexaminstance_id) REFERENCES public.exams_temporaryexaminstance(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exams_temporaryexaminstance exams_temporaryexaminstance_exam_id_6d734dda_fk_exams_exam_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_temporaryexaminstance
    ADD CONSTRAINT exams_temporaryexaminstance_exam_id_6d734dda_fk_exams_exam_id FOREIGN KEY (exam_id) REFERENCES public.exams_exam(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: exams_temporaryexaminstance exams_temporaryexaminstance_track_id_a4a6109f_fk_users_track_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exams_temporaryexaminstance
    ADD CONSTRAINT exams_temporaryexaminstance_track_id_a4a6109f_fk_users_track_id FOREIGN KEY (track_id) REFERENCES public.users_track(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labs_lab labs_lab_instructor_id_736a7990_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labs_lab
    ADD CONSTRAINT labs_lab_instructor_id_736a7990_fk_users_user_id FOREIGN KEY (instructor_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: labs_lab labs_lab_track_id_c6377096_fk_users_track_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.labs_lab
    ADD CONSTRAINT labs_lab_track_id_c6377096_fk_users_track_id FOREIGN KEY (track_id) REFERENCES public.users_track(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: social_auth_usersocialauth social_auth_usersocialauth_user_id_17d28448_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.social_auth_usersocialauth
    ADD CONSTRAINT social_auth_usersocialauth_user_id_17d28448_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: st_notifications_note st_notifications_not_instructor_id_2272f5de_fk_users_ins; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.st_notifications_note
    ADD CONSTRAINT st_notifications_not_instructor_id_2272f5de_fk_users_ins FOREIGN KEY (instructor_id) REFERENCES public.users_instructor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: st_notifications_note st_notifications_note_student_id_7a1ea08a_fk_users_student_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.st_notifications_note
    ADD CONSTRAINT st_notifications_note_student_id_7a1ea08a_fk_users_student_id FOREIGN KEY (student_id) REFERENCES public.users_student(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: st_notifications_note st_notifications_note_track_id_7ed19623_fk_users_track_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.st_notifications_note
    ADD CONSTRAINT st_notifications_note_track_id_7ed19623_fk_users_track_id FOREIGN KEY (track_id) REFERENCES public.users_track(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: st_notifications_pushsubscription st_notifications_pus_user_id_a1254722_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.st_notifications_pushsubscription
    ADD CONSTRAINT st_notifications_pus_user_id_a1254722_fk_users_use FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_course users_course_instructor_id_64a94160_fk_users_instructor_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_course
    ADD CONSTRAINT users_course_instructor_id_64a94160_fk_users_instructor_id FOREIGN KEY (instructor_id) REFERENCES public.users_instructor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_course users_course_track_id_b6f335bc_fk_users_track_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_course
    ADD CONSTRAINT users_course_track_id_b6f335bc_fk_users_track_id FOREIGN KEY (track_id) REFERENCES public.users_track(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_instructor users_instructor_branch_id_2a24d57f_fk_users_branch_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_instructor
    ADD CONSTRAINT users_instructor_branch_id_2a24d57f_fk_users_branch_id FOREIGN KEY (branch_id) REFERENCES public.users_branch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_instructor users_instructor_user_id_7b00976e_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_instructor
    ADD CONSTRAINT users_instructor_user_id_7b00976e_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_student users_student_branch_id_67ef876d_fk_users_branch_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_student
    ADD CONSTRAINT users_student_branch_id_67ef876d_fk_users_branch_id FOREIGN KEY (branch_id) REFERENCES public.users_branch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_student users_student_track_id_bdc09d87_fk_users_track_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_student
    ADD CONSTRAINT users_student_track_id_bdc09d87_fk_users_track_id FOREIGN KEY (track_id) REFERENCES public.users_track(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_student users_student_user_id_dc59cd64_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_student
    ADD CONSTRAINT users_student_user_id_dc59cd64_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_track_instructors users_track_instruct_instructor_id_95191c73_fk_users_ins; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_track_instructors
    ADD CONSTRAINT users_track_instruct_instructor_id_95191c73_fk_users_ins FOREIGN KEY (instructor_id) REFERENCES public.users_instructor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_track_instructors users_track_instructors_track_id_a895d887_fk_users_track_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_track_instructors
    ADD CONSTRAINT users_track_instructors_track_id_a895d887_fk_users_track_id FOREIGN KEY (track_id) REFERENCES public.users_track(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

