# Generated by Django 5.1.7 on 2025-05-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheatingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('starter_code', models.TextField(default='None')),
                ('source', models.CharField(max_length=100)),
                ('points', models.FloatField(default=1.0)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('xml', 'XML'), ('sql', 'SQL'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('php', 'PHP'), ('razor', 'Razor'), ('markdown', 'Markdown'), ('yaml', 'YAML'), ('shell', 'Shell'), ('powershell', 'PowerShell'), ('lua', 'Lua'), ('r', 'R'), ('perl', 'Perl'), ('swift', 'Swift'), ('objective-c', 'Objective-C'), ('scss', 'SCSS'), ('less', 'LESS')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CodingTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('function_name', models.CharField(blank=True, default='', help_text='Name of the function to test (leave blank for single-function questions)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(blank=True, max_length=255, null=True)),
                ('option_d', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('xml', 'XML'), ('sql', 'SQL'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('php', 'PHP'), ('razor', 'Razor'), ('markdown', 'Markdown'), ('yaml', 'YAML'), ('shell', 'Shell'), ('powershell', 'PowerShell'), ('lua', 'Lua'), ('r', 'R'), ('perl', 'Perl'), ('swift', 'Swift'), ('objective-c', 'Objective-C'), ('scss', 'SCSS'), ('less', 'LESS')], max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('points', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compressed_answers', models.BinaryField()),
                ('score', models.FloatField(default=0.0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryExamInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
    ]
