# Generated by Django 5.1.7 on 2025-05-14 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatinglog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codingtestcase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='exams.codingquestion'),
        ),
        migrations.AddField(
            model_name='exam',
            name='CodingQuestions',
            field=models.ManyToManyField(blank=True, to='exams.codingquestion'),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='users.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='MCQQuestions',
            field=models.ManyToManyField(blank=True, to='exams.mcqquestion'),
        ),
        migrations.AddField(
            model_name='studentexamanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to='users.student'),
        ),
        migrations.AddField(
            model_name='temporaryexaminstance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_instances', to='users.branch'),
        ),
        migrations.AddField(
            model_name='temporaryexaminstance',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='temporaryexaminstance',
            name='instructor_id',
            field=models.ForeignKey(db_column='instructor_id', default=5, on_delete=django.db.models.deletion.CASCADE, to='users.instructor'),
        ),
        migrations.AddField(
            model_name='temporaryexaminstance',
            name='students',
            field=models.ManyToManyField(blank=True, to='users.student'),
        ),
        migrations.AddField(
            model_name='temporaryexaminstance',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.track'),
        ),
        migrations.AddField(
            model_name='studentexamanswer',
            name='exam_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='exams.temporaryexaminstance'),
        ),
    ]
